(straight-use-package 'helm)
(straight-use-package 'zenburn-theme)
(straight-use-package 'recentf-ext)
(straight-use-package 'projectile)
(straight-use-package 'helm-projectile)
(straight-use-package 'magit)
(straight-use-package 'dashboard)
