(straight-use-package 'helm)
(straight-use-package 'solarized-theme)
(straight-use-package 'recentf-ext)
(straight-use-package 'projectile)
(straight-use-package 'helm-projectile)
(straight-use-package 'magit)
