(straight-use-package 'ivy)
(straight-use-package 'counsel)
(straight-use-package 'swiper)
(straight-use-package 'afternoon-theme)
(straight-use-package 'recentf-ext)
(straight-use-package 'projectile)
(straight-use-package 'counsel-projectile)
(straight-use-package 'magit)
(straight-use-package 'dashboard)
(straight-use-package 'company)
(straight-use-package 'autopair)
(straight-use-package 'popwin)
(straight-use-package 'powerline)

;; language modes
(straight-use-package 'rust-mode)
(straight-use-package 'go-mode)
(straight-use-package 'ruby-mode)
(straight-use-package 'scala-mode)
(straight-use-package 'typescript-mode)
(straight-use-package 'vue-mode)
(straight-use-package 'pug-mode)
